# Generated by Django 5.1.15 on 2026-03-24 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voter',
            options={},
        ),
    ]
