# Generated by Django 5.1.15 on 2026-03-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0002_remove_voter_default_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurerequest',
            name='status',
            field=models.CharField(choices=[('under_review', 'Under Review'), ('planned', 'Planned'), ('in_progress', 'In Progress'), ('shipped', 'Shipped')], db_index=True, default='under_review', max_length=20),
        ),
    ]
