# Generated by Django 5.1.15 on 2026-03-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_swap_voter_for_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featurerequest',
            options={'ordering': ['-is_pinned', '-vote_count', '-created_at']},
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
